// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: server/protobuf/news.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NewServiceClient is the client API for NewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NewServiceClient interface {
	GetHotTopNews(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type newServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNewServiceClient(cc grpc.ClientConnInterface) NewServiceClient {
	return &newServiceClient{cc}
}

func (c *newServiceClient) GetHotTopNews(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protobuf.NewService/GetHotTopNews", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NewServiceServer is the server API for NewService service.
// All implementations must embed UnimplementedNewServiceServer
// for forward compatibility
type NewServiceServer interface {
	GetHotTopNews(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedNewServiceServer()
}

// UnimplementedNewServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNewServiceServer struct {
}

func (UnimplementedNewServiceServer) GetHotTopNews(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHotTopNews not implemented")
}
func (UnimplementedNewServiceServer) mustEmbedUnimplementedNewServiceServer() {}

// UnsafeNewServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NewServiceServer will
// result in compilation errors.
type UnsafeNewServiceServer interface {
	mustEmbedUnimplementedNewServiceServer()
}

func RegisterNewServiceServer(s grpc.ServiceRegistrar, srv NewServiceServer) {
	s.RegisterService(&NewService_ServiceDesc, srv)
}

func _NewService_GetHotTopNews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewServiceServer).GetHotTopNews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.NewService/GetHotTopNews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewServiceServer).GetHotTopNews(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// NewService_ServiceDesc is the grpc.ServiceDesc for NewService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NewService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.NewService",
	HandlerType: (*NewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHotTopNews",
			Handler:    _NewService_GetHotTopNews_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/protobuf/news.proto",
}
